server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hr
    username: nick
    password: root
logging:
  level:
    com.syt.springbootee: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml